theme: minima
title: life in musik
author: Whislte52
email: liuyihan095@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  sometimes i'm so desire to merge myself into musik...

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
